{% set version="3.8" %}

about:
  home: https://www.broadinstitute.org/gatk/
  license: BSD
  summary: The full Genome Analysis Toolkit (GATK) framework

package:
  name: gatk
  version: {{ version }}

build:
  number: 3
  skip: False

source:
    fn: GenomeAnalysisTK-{{ version }}.tar.gz
    url: https://software.broadinstitute.org/gatk/download/auth?package=GATK
    sha256: d1017b851f0cc6442b75ac88dd438e58203fa3ef1d1c38eb280071ae3803b9f1

requirements:
  run:
    - openjdk >=8,<9
    - python
    - r-gplots
    - r-ggplot2
    - r-gsalib
    - r-reshape

test:
  commands:
    - "GenomeAnalysisTK --version"

